### ISSUE TITLE
Hazelcast Docker run issue [rest api not enabled]

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [hazelcast/hazelcast-docker#244]
I am using the below docker-compose file to run the Hazelcast on docker but keep getting the Rest API not enabled error. I have tried to provide the java arguments but still, it is not working. Following are the details -

_docker-compose file_
```
services: 
  mongodb: 
    container_name: dockerhazel
    environment: 
      JAVA_OPTS: "-Dhazelcast.local.publicAddress=localhost:5701 -Dhazelcast.rest.enabled=true"
    image: hazelcast/hazelcast
    ports: 
      - "5701:5701"
version: "3"
```

_logs_ -
```
dockerhazel |   at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel | 2021-02-25 09:54:28,116 [ WARN] [hz.angry_jang.IO.thread-in-2] [c.h.i.s.t.TcpServerConnection]: [localhost]:5701 [dev] [4.1.1] Connection[id=12, /172.18.0.2:5701->/172.18.0.1:59642, qualifier=null, endpoint=null,
 alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Exception in Connection[id=12, /172.18.0.2:5701->/172.18.0.1:59642, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1], thread=hz.an
gry_jang.IO.thread-in-2
dockerhazel | java.lang.IllegalStateException: REST API is not enabled.
dockerhazel |   at com.hazelcast.internal.server.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:106) ~[hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:137) ~[hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.networking.nio.NioPipeline.lambda$start$0(NioPipeline.java:127) ~[hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:355) [hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:290) [hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) [hazelcast-all-4.1.1.jar:4.1.1]
dockerhazel |   at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-all-4.1.1.jar:4.1.1]
```

_browser_ -
![image](https://user-images.githubusercontent.com/46935197/109136225-e9ad5400-777d-11eb-8468-1e32c0bc8197.png)

please check and suggest.

**Comment by hasancelik** [comment]
Hi @beena-yatin-kanyal,

`hazelcast.rest.enabled` is [deprecated](https://docs.hazelcast.com/imdg/latest/migration-guides.html#removal-of-deprecated-system-properties) so you need to enable it via YAML/XML file or enviroment variable like I did below:
```
version: "3"
services:
  hazelcast:
    image: hazelcast/hazelcast:4.1.1
    environment:
      HZ_NETWORK_PUBLICADDRESS: "127.0.0.1:5701"
      HZ_NETWORK_RESTAPI_ENABLED: "true"
    ports:
      - 5701:5701
```
```
$ curl -X GET http://127.0.0.1:5701/hazelcast/rest/cluster
{"members":[{"address":"[127.0.0.1]:5701","liteMember":false,"localMember":true,"uuid":"e09b18b8-bf52-4e04-98f6-51d62ae9fbea","memberVersion":"4.1.1"}],"connectionCount":1,"allConnectionCount":1}
```
You can check related documentation from [here](https://docs.hazelcast.com/imdg/latest/configuration/overriding-configuration-settings.html)

**Comment by beena-yatin-kanyal** [comment]
thanks, @hasancelik for your help. However, it seems to an issue with the latest docker image for hazelcast and management center as I was running into trouble while running the _mc-conf.sh_ script in order to create a _default dev cluster_ for poc purpose. Here is the docker-compose.yml file I used to get things up and running -

```
services: 
  hazelcast: 
    container_name: hazelcast
    environment: 
      HZ_NETWORK_PUBLICADDRESS: "127.0.0.1:5701"
      HZ_NETWORK_RESTAPI_ENABLED: "true"
    image: "hazelcast/hazelcast:4.0.1"
    ports: 
      - "5701:5701"
  management-center: 
    container_name: management-center
    depends_on: 
      - hazelcast
    environment: 
      MC_ADMIN_PASSWORD: somepassword@11
      MC_ADMIN_USER: someadminuser
      MC_INIT_CMD: "./mc-conf.sh cluster add -H=/data -ma hazelcast:5701 -cn dev"
    image: "hazelcast/management-center:4.0.3"
    ports: 
      - "10080:8080"
version: "3"
```
