### ISSUE TITLE
cannot get endpoints in the namespace "default"

### ISSUE THREAD

**Issue by XieXianbin** [hazelcast/hazelcast-docker#53]
SEVERE: [172.20.215.2]:5701 [dev] [3.9.2] Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/hazelcast. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. endpoints "hazelcast" is forbidden: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/hazelcast. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. endpoints "hazelcast" is forbidden: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:787)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:217)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:184)
	at com.hazelcast.kubernetes.ServiceEndpointResolver.resolve(ServiceEndpointResolver.java:81)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:102)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70)
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:59)
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:131)
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:90)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:134)
	at com.hazelcast.instance.Node.join(Node.java:690)
	at com.hazelcast.instance.Node.start(Node.java:390)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.core.server.StartServer.main(StartServer.java:46)

Jan 15, 2018 3:36:53 AM com.hazelcast.instance.Node
SEVERE: [172.20.215.2]:5701 [dev] [3.9.2] Could not join cluster in 300000 ms. Shutting down now!

**Comment by googlielmo** [comment]
Hi @XieXianbin 
This usually happens when the proper authorizations are missing for User "system:serviceaccount:default:default" in your Kubernetes cluster.
See https://github.com/fabric8io/fabric8/issues/6840#issuecomment-307560275 for a solution.
Closing this as solved. Feel free to reopen if needed.

**Comment by artem-zinnatullin** [comment]
Hey guys, I wonder why hazelcast nodes need `admin` access to kubernetes api? 

Security and k8s teams at my company definitely won't be happy if I'll try to deploy Hazelcast cluster with such privileges. 

I was choosing between Hazelcast and Apache Ignite and chose Hazelcast for multiple reasons, but this `admin` thing might just force me to use Ignite for now because they don't require that https://apacheignite.readme.io/docs/kubernetes-deployment

I suppose you need admin for autodiscovery (please correct me if I'm wrong), maybe a separate service [like Ignite does](https://apacheignite.readme.io/docs/kubernetes-deployment#section-kubernetes-ignite-lookup-service) will be a better solution?

Is there a way to not require such privileges?

Thanks!

**Comment by artem-zinnatullin** [comment]
Moreover PR #71 now recommends to grant admin privileges to all pods in the cluster (!) if I understand it correctly:

```yaml
Then you have to grant authorization, so the pods can connect Kubernetes' API. Create a new file hazelcast-rbac.yaml with this content:

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

and then apply the changes:

$ kubectl apply -f hazelcast-rbac.yaml

after a few seconds you'll see the pods up and running and you'll able to use your new Hazelcast cluster.
```

That sounds like veery bad security practice…
