### ISSUE TITLE
eval JAVA_OPTS in start.sh

### ISSUE THREAD

**Issue by dacleyra** [hazelcast/hazelcast-docker#61]
In a kubernetes environment one may want to
- set an environmental variable via helm, etc.
- consume that environmental variable as part of JAVA_OPTS

An eval should allow the JAVA_OPTS to resolve the env var

```
          env:
          - name: KEYSTORE_PASSWORD
            value: {{ .Values.keystorePassword}}
          - name: JAVA_OPTS
            value: "-DkeystorePassword=${KEYSTORE_PASSWORD}"
```

As an example, this is a convenience that is currently used in OpenLiberty

https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L826
